### PR TITLE
Parenchyma analysis segmentation support

### PR DESCRIPTION
**Pull request by lassoan**
This pull request includes https://github.com/acil-bwh/SlicerCIP/pull/32 and adds further fixes (such as report generation), design improvements and code refactoring.

@rbumm please test if everything works as expected. I've changed the API of the logic class, so you may need to adjust Lung CT Segmenter module accordingly.

### CODE REVIEW

**Comment by rbumm** [comment]
Very good, all works well. The Lung CT Segmenter has no labelmap output anymore and does not interact with the logic of Parenchyma Analysis.

**Comment by lassoan** [comment]
Great, thanks @rbumm for testing.

@rjosest it would be great if you could merge this.

**Comment by lassoan** [comment]
@rjosest it would be great if you could merge this.

**Comment by lassoan** [comment]
The pull request now includes a fix for a build error that is caused by recent Slicer API updates (removal of an obsolete class).

**Comment by lassoan** [comment]
@rjosest Please merge. The fix is required for SlicerCIP extension to appear in the extensions manager. To allow keeping SlicerCIP extension functional when Slicer API changes, without the need for you to review and approve each pull request, you may consider granting me write access to this repository.

**Comment by lassoan** [comment]
@rjosest Please merge. Thank you!

**Comment by rbumm** [comment]
Yes, would be great if the merge could be done.

**Comment by rjosest** [comment]
@lassoan @rbumm  Thank you for this fix and my apologies for missing the merge. I reviewed the changes and look good from my end.

**Pull request merged**
